Makefile: add relase-hook to verify release is tagged
Signed-off-by: Joachim Wiberg <troglobit@gmail.com>

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -34,9 +34,29 @@ systemd_DATA   = syslogd.service
 endif
 
 #
+# Check if tagged in git
+#
+release-hook:
+	@if [ ! `git tag | grep $(PACKAGE_VERSION)` ]; then				\
+		echo;									\
+		printf "\e[1m\e[41mCannot find release tag $(PACKAGE_VERSION)\e[0m\n";	\
+		printf "\e[1m\e[5mDo release anyway?\e[0m "; read yorn;			\
+		if [ "$$yorn" != "y" -a "$$yorn" != "Y" ]; then				\
+			printf "OK, aborting release.\n";				\
+			exit 1;								\
+		fi;									\
+		echo;									\
+	else										\
+		echo;									\
+		printf "\e[1m\e[42mFound GIT release tag $(PACKAGE_VERSION)\e[0m\n";	\
+		printf "\e[1m\e[44m>>Remember to push tags!\e[0m\n";			\
+		echo;									\
+	fi
+
+#
 # Target to run when building a release
 #
-release: distcheck
+release: release-hook distcheck
 	@for file in $(DIST_ARCHIVES); do		\
 		md5sum    $$file > ../$$file.md5;	\
 		sha256sum $$file > ../$$file.sha256;	\
