Revert "Extract version from GIT, inspiration from mdio-tools"
This reverts commit da7425f757076fb4e7317963fef8084de1b91fad.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -25,10 +25,9 @@
 # OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 # SUCH DAMAGE.
 
+SUBDIRS        = example man src test
 doc_DATA       = README.md LICENSE ChangeLog.md syslog.conf
 EXTRA_DIST     = README.md LICENSE ChangeLog.md syslog.conf
-SUBDIRS        = example man src test
-TAG            = $(top_srcdir)/.git/refs/tags/$(PACKAGE_VERSION)
 
 if HAVE_SYSTEMD
 systemd_DATA   = syslogd.service
@@ -37,9 +36,22 @@ endif
 #
 # Check if tagged in git
 #
-$(TAG):
-	@printf "\e[1m\e[41mPlease create the \"$(PACKAGE_VERSION)\" tag first\e[0m\n"
-	@exit 1
+release-hook:
+	@if [ ! `git tag -l v$(PACKAGE_VERSION) | grep $(PACKAGE_VERSION)` ]; then	\
+		echo;									\
+		printf "\e[1m\e[41mCannot find release tag $(PACKAGE_VERSION)\e[0m\n";	\
+		printf "\e[1m\e[5mDo release anyway?\e[0m "; read yorn;			\
+		if [ "$$yorn" != "y" -a "$$yorn" != "Y" ]; then				\
+			printf "OK, aborting release.\n";				\
+			exit 1;								\
+		fi;									\
+		echo;									\
+	else										\
+		echo;									\
+		printf "\e[1m\e[42mFound GIT release tag $(PACKAGE_VERSION)\e[0m\n";	\
+		printf "\e[1m\e[44m>>Remember to push tags!\e[0m\n";			\
+		echo;									\
+	fi
 
 #
 # Generate .deb package(s)
